"""
CZR DNA Scrapers — Orchestrator
Runs all 4 model scrapers sequentially and writes a combined digest.

Usage:
    python3 -m dna.scrapers.run           # run all, write reports
    python3 -m dna.scrapers.run --model vogue  # single model
    python3 -m dna.scrapers.run --digest       # print latest digest
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

REPORTS = Path(__file__).parent / "reports"
REPORTS.mkdir(exist_ok=True)


def run_model(name: str) -> dict | None:
    try:
        if name == "vogue":
            from dna.scrapers.vogue import scrape, write_report
        elif name == "hermes":
            from dna.scrapers.hermes import scrape, write_report
        elif name == "spacex":
            from dna.scrapers.spacex import scrape, write_report
        elif name == "apple":
            from dna.scrapers.apple import scrape, write_report
        else:
            print(f"  ❌ Unknown model: {name}")
            return None

        data   = scrape()
        report = write_report(data, REPORTS)
        print(f"  ✅ {name.capitalize():10} → {report.name}")
        return data
    except Exception as e:
        print(f"  ❌ {name.capitalize()} failed: {e}")
        return None


def write_digest(all_data: list[dict]) -> Path:
    """A single combined digest of all 4 models' signals for this run."""
    date = datetime.now().strftime("%Y%m%d_%H%M")
    path = REPORTS / f"digest_{date}.md"
    lines = [
        f"# CZR DNA Model Research Digest — {datetime.now().strftime('%B %d, %Y')}",
        "",
        "> Auto-generated by `dna.scrapers.run`.",
        "> Review signals below. Update `dna/models.md` if patterns have shifted.",
        "",
    ]
    for data in all_data:
        if not data:
            continue
        model = data.get("model", "Unknown")
        signals = data.get("czr_signals", [])
        lines += [f"## {model}", ""]
        if signals:
            lines += [f"- {s}" for s in signals]
        else:
            lines += ["- No new signals detected."]
        lines += [""]
    lines += ["---", f"_Generated: {datetime.now().isoformat()}_"]
    path.write_text("\n".join(lines))
    return path


def print_latest_digest():
    digests = sorted(REPORTS.glob("digest_*.md"), reverse=True)
    if not digests:
        print("No digest found. Run `python3 -m dna.scrapers.run` first.")
        return
    print(digests[0].read_text())


def main():
    parser = argparse.ArgumentParser(description="CZR DNA Model Scrapers")
    parser.add_argument("--model", choices=["vogue", "hermes", "spacex", "apple"],
                        help="Run a single model scraper")
    parser.add_argument("--digest", action="store_true",
                        help="Print the latest digest report")
    args = parser.parse_args()

    if args.digest:
        print_latest_digest()
        return

    models = [args.model] if args.model else ["vogue", "hermes", "spacex", "apple"]

    print("=" * 60)
    print("CZR DNA — Model Research Scrape")
    print(f"Models: {', '.join(m.capitalize() for m in models)}")
    print("=" * 60)

    all_data = [run_model(m) for m in models]

    if len(models) > 1:
        digest = write_digest([d for d in all_data if d])
        print()
        print(f"📋 Digest written: {digest.name}")
        print()
        print("Next: review signals and update dna/models.md if needed.")
        print("Then: python3 -m dna.sync to propagate changes.")
    print("=" * 60)


if __name__ == "__main__":
    main()
